#!/usr/bin/env bash
#script that displays the PID, along with the process name, of processes whose name contain the word bash.

for pid in /proc/[0-9]; do
	pid="${pid#/proc/}"
	if [ -f "/proc/$pid/comm" ]; then
		proc_name=$(cat "/proc/$pid/comm")
		if echo "$proc_name" | grep -q "bash"; then
			echo "$pid $proc_name"
		fi
	fi
done
